#!/bin/bash

py=${WD_PYTHON_PATH:-python3}
pager=${WD_PAGER_COMMAND}

count=`ps -ef | grep "python3 WudaoServer.py" | grep -v "grep" | wc -l`
 
if [ $count == 0 ]; then
    nohup $py WudaoServer.py > ./usr/server.log 2>&1 &
    git pull origin master > ./usr/pull.log 2>&1 &
fi

if [[ -n "${pager}" ]]; then
    $py WudaoCommand.py $* | $pager
else
    $py WudaoCommand.py $*
fi

