#!/bin/bash

count=`ps -ef | grep "python3 WudaoServer.py" | grep -v "grep" | wc -l`
 
if [ $count == 0 ]; then
    nohup python3 WudaoServer.py > ./usr/server.log 2>&1 &
fi

python3 WudaoCommand.py $*

